### PR TITLE
Adding front end test details

### PR DESCRIPTION
**Pull request by mikefogg**

### CODE REVIEW

**Comment by bploetz** [comment]
@mikefogg LGTM!

**Comment by jgandt** [comment]
Same! LGTMT! (actually I didn't look...)

(I already told Dan and Ev that I'm still on this repo. If one of you feels
like removing me, go for it.)

.jpg

**Comment by bploetz** [comment]
@jgandt Both Dan and Ev forwarded your email to me, but I don't actually see you in the list of users on this repo......trying to figure out why you still have access.

**Comment by bploetz** [comment]
@jgandt no one else can find you either, so this may be a Github bug. I'll open a support case for it.

Sorry for the spam.

**Pull request merged**
